apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace for the operator and instance.
namespace: api-designer

# Namespace and operator resources.
resources:
  - namespace.yaml
  - fuse-apicurito-subscription.yaml
  - fuse-apicurito-operatorgroup.yaml
