apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace for the operator and instance.
namespace: microcks

# Namespace and operator resources.
resources:
  - namespace.yaml
  - microcks-operatorgroup.yaml
  - microcks-subscription.yaml
  - strimzi-kafka-operator-subscription.yaml
