apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: CheCluster.v1.org.eclipse.che
  name: openshift-workspaces
spec:
  targetNamespaces:
  - openshift-workspaces
